### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by aaronliu0130**
Add those so we can test the program.
~~Also to add a test stanza for the homebrew formula~~

### CODE REVIEW

**Comment by aaronliu0130** [comment]
@stefanhaustein Requesting review.

**Comment by stefanhaustein** [comment]
Is there any license associated with the images we need to care about / take into account?

**Comment by aaronliu0130** [comment]
The cornell box doesn't have any license. However, the shepp-logan phantom does have the [Creative Commons Attribution-Share Alike 4.0 International license.](https://creativecommons.org/licenses/by-sa/4.0/deed.en)

> You are free:
to share – to copy, distribute and transmit the work
to remix – to adapt the work
Under the following conditions:
attribution – You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
share alike – If you remix, transform, or build upon the material, you must distribute your contributions under the same or compatible license as the original.

So we need to "give appropriate credit" and "provide a link to the license". We don't need to indicate if changes were made or satisfy the "share alike" condition, because we didn't change it.

**Comment by aaronliu0130** [comment]
Ok. Added the license in a commit. Is that okay?

**Comment by stefanhaustein** [comment]
Don't we need to reference the license somewhere permanently (= in our own license -- opposed to just the commit message)? Could we avoid the whole licensing fuss by just using our own test image(s)? Do they have any special requirements? Ideally our own license would stay plain vanilla Apache 2.0.....

**Comment by aaronliu0130** [comment]
Huh. Good idea. I'll do it later because I don't have time now.

**Comment by aaronliu0130** [comment]
Had another solution. Now it's just public domain. Good now, right @stefanhaustein ?

**Comment by stefanhaustein** [comment]
According to wikipededia, the file is licensed under the "Creative Commons Attribution-Share Alike 3.0 Unported license.": https://commons.wikimedia.org/wiki/File:Shepp_logan.png

**Comment by aaronliu0130** [comment]
But the cornell box is public domain!

**Pull request closed without merging**
