### PR TITLE
Refactored, added gradle, tiv and cats scripts.

### PR DESCRIPTION
**Pull request by wieczorek1990**

### CODE REVIEW

**Comment by stefanhaustein** [comment]
Thanks a lot! Would you mind avoiding the extra dependencies in TerminalImageViewer.java? I'd really prefer to keep it usable standalone....

**Comment by wieczorek1990** [comment]
Yeah, I thought you would like not to use any dependencies, but used it anyway not to have write the same boilerplate code again. Will check later if I can get rid of JCommander.

**Comment by stefanhaustein** [comment]
Any update? O:) 
Wondering if it might be easier to just add cats support to the java main?

**Comment by wieczorek1990** [comment]
Bump.

**Comment by stefanhaustein** [comment]
Thanks! It's still a lot of stuff in a single PR.... I'll probably pull in some of the code improvements manually first. I'll probably also add a slideshow option (that would cycle through the urls/file names with a given delay).

**Comment by stefanhaustein** [comment]
Is a namespace required for gradle?
I know usually there should be one, but I wanted to keep this as simple as possible, given that this is a command line tool and not a library....

**Comment by wieczorek1990** [comment]
If you mean the directory structure, then it works without a tree just with a `package` statement in the source file.

**Comment by stefanhaustein** [comment]
Hi, I am closing this because I have finally switched to C++ (including a simple way to install using make).

**Pull request closed without merging**
