### PR TITLE
Templates+Homebrew Non-deprecated Installation option

### PR DESCRIPTION
**Pull request by aaronliu0130**
Adds issue and PR templates.

### CODE REVIEW

**Comment by stefanhaustein** [comment]
Pull requests that combine multiple things are hard to review.

The number of issues seems to be low enough to just use the default templates?

**Comment by aaronliu0130** [comment]
> The number of issues seems to be low enough to just use the default templates?

I'm pretty sure github does not have "default templates" if you don't add them.

**Comment by aaronliu0130** [comment]
@stefanhaustein please review

**Comment by stefanhaustein** [comment]
Please don't send pull requests that combine multiple things. 

I don't think an explicit template is needed at this point.

**Comment by aaronliu0130** [comment]
Alright. I'll split them.

**Pull request closed without merging**
