### PR TITLE
Upgrade CImg to v2.3.3

### PR DESCRIPTION
**Pull request by hadisfr**
https://github.com/dtschump/CImg/releases/tag/v.2.3.3

### CODE REVIEW

**Comment by hadisfr** [comment]
Please merge #26 before merging this, so merge commit for this pull request only effects _CImg.h_ file.

**Comment by hadisfr** [comment]
Now this PR only changes one file. :D

**Comment by HybridDog** [comment]
You could use git subtree to keep a clean history.

**Comment by hadisfr** [comment]
@HybridDog Actually I didn't know anything about subtree. First I thought using submodule, but finally I decided not to use it because the whole repo of _CImg_ was big and also, I didn't want to change directory structure of this projects. But it may be a better idea than what I did.

**Pull request merged**
